#include <tavros/system/platform/macos/utils.hpp>

using namespace tavros::system;

keys tavros::system::map_key(uint16 key_code) noexcept
{
    switch (key_code) {
    case 0x1D:
        return keys::k_0;
    case 0x12:
        return keys::k_1;
    case 0x13:
        return keys::k_2;
    case 0x14:
        return keys::k_3;
    case 0x15:
        return keys::k_4;
    case 0x17:
        return keys::k_5;
    case 0x16:
        return keys::k_6;
    case 0x1A:
        return keys::k_7;
    case 0x1C:
        return keys::k_8;
    case 0x19:
        return keys::k_9;
    case 0x00:
        return keys::k_A;
    case 0x0B:
        return keys::k_B;
    case 0x08:
        return keys::k_C;
    case 0x02:
        return keys::k_D;
    case 0x0E:
        return keys::k_E;
    case 0x03:
        return keys::k_F;
    case 0x05:
        return keys::k_G;
    case 0x04:
        return keys::k_H;
    case 0x22:
        return keys::k_I;
    case 0x26:
        return keys::k_J;
    case 0x28:
        return keys::k_K;
    case 0x25:
        return keys::k_L;
    case 0x2E:
        return keys::k_M;
    case 0x2D:
        return keys::k_N;
    case 0x1F:
        return keys::k_O;
    case 0x23:
        return keys::k_P;
    case 0x0C:
        return keys::k_Q;
    case 0x0F:
        return keys::k_R;
    case 0x01:
        return keys::k_S;
    case 0x11:
        return keys::k_T;
    case 0x20:
        return keys::k_U;
    case 0x09:
        return keys::k_V;
    case 0x0D:
        return keys::k_W;
    case 0x07:
        return keys::k_X;
    case 0x10:
        return keys::k_Y;
    case 0x06:
        return keys::k_Z;
    case 0x27:
        return keys::k_apostrophe;
    case 0x2A:
        return keys::k_backslash;
    case 0x2B:
        return keys::k_comma;
    case 0x18:
        return keys::k_equal;
    case 0x32:
        return keys::k_grave_accent;
    case 0x21:
        return keys::k_lbracket;
    case 0x1B:
        return keys::k_minus;
    case 0x2F:
        return keys::k_period;
    case 0x1E:
        return keys::k_rbracket;
    case 0x29:
        return keys::k_semicolon;
    case 0x2C:
        return keys::k_slash;
    case 0x33:
        return keys::k_backspace;
    case 0x39:
        return keys::k_capslock;
    case 0x75:
        return keys::k_delete;
    case 0x77:
        return keys::k_end;
    case 0x24:
        return keys::k_enter;
    case 0x35:
        return keys::k_escape;
    case 0x7A:
        return keys::k_F1;
    case 0x78:
        return keys::k_F2;
    case 0x63:
        return keys::k_F3;
    case 0x76:
        return keys::k_F4;
    case 0x60:
        return keys::k_F5;
    case 0x61:
        return keys::k_F6;
    case 0x62:
        return keys::k_F7;
    case 0x64:
        return keys::k_F8;
    case 0x65:
        return keys::k_F9;
    case 0x6D:
        return keys::k_F10;
    case 0x67:
        return keys::k_F11;
    case 0x6F:
        return keys::k_F12;
    case 0x6B:
        return keys::k_F14;
    case 0x71:
        return keys::k_F15;
    case 0x6A:
        return keys::k_F16;
    case 0x40:
        return keys::k_F17;
    case 0x4F:
        return keys::k_F18;
    case 0x50:
        return keys::k_F19;
    case 0x5A:
        return keys::k_F20;
    case 0x69:
        return keys::k_print_screen;
    case 0x73:
        return keys::k_home;
    case 0x72:
        return keys::k_insert;
    case 0x3A:
        return keys::k_lalt;
    case 0x3B:
        return keys::k_lcontrol;
    case 0x38:
        return keys::k_lshift;
    case 0x37:
        return keys::k_lsuper;
    case 0x47:
        return keys::k_numlock;
    case 0x79:
        return keys::k_pagedown;
    case 0x74:
        return keys::k_pageup;
    case 0x7B:
        return keys::k_left;
    case 0x7C:
        return keys::k_right;
    case 0x7D:
        return keys::k_down;
    case 0x7E:
        return keys::k_up;
    case 0x3D:
        return keys::k_ralt;
    case 0x3E:
        return keys::k_rcontrol;
    case 0x3C:
        return keys::k_rshift;
    case 0x36:
        return keys::k_rsuper;
    case 0x31:
        return keys::k_space;
    case 0x30:
        return keys::k_tab;
    case 0x52:
        return keys::k_numpad0;
    case 0x53:
        return keys::k_numpad1;
    case 0x54:
        return keys::k_numpad2;
    case 0x55:
        return keys::k_numpad3;
    case 0x56:
        return keys::k_numpad4;
    case 0x57:
        return keys::k_numpad5;
    case 0x58:
        return keys::k_numpad6;
    case 0x59:
        return keys::k_numpad7;
    case 0x5B:
        return keys::k_numpad8;
    case 0x5C:
        return keys::k_numpad9;
    case 0x45:
        return keys::k_add;
    case 0x41:
        return keys::k_decimal;
    case 0x4B:
        return keys::k_divide;
    case 0x4C:
        return keys::k_enter;
    case 0x43:
        return keys::k_multiply;
    case 0x4E:
        return keys::k_subtract;
    default:
        return keys::none;
    }
}
