#include <tavros/input/utils.hpp>

#include <tavros/core/debug/unreachable.hpp>

namespace tavros::input
{

    core::string_view to_string(keyboard_key key) noexcept
    {
        switch (key) {
        case keyboard_key::none:
            return "none";
        case keyboard_key::k_lbutton:
            return "k_lbutton";
        case keyboard_key::k_rbutton:
            return "k_rbutton";
        case keyboard_key::k_break:
            return "k_break";
        case keyboard_key::k_mbutton:
            return "k_mbutton";
        case keyboard_key::k_xbutton1:
            return "k_xbutton1";
        case keyboard_key::k_xbutton2:
            return "k_xbutton2";
        case keyboard_key::k_backspace:
            return "k_backspace";
        case keyboard_key::k_tab:
            return "k_tab";
        case keyboard_key::k_enter:
            return "k_enter";
        case keyboard_key::k_pause:
            return "k_pause";
        case keyboard_key::k_capslock:
            return "k_capslock";
        case keyboard_key::k_escape:
            return "k_escape";
        case keyboard_key::k_space:
            return "k_space";
        case keyboard_key::k_pageup:
            return "k_pageup";
        case keyboard_key::k_pagedown:
            return "k_pagedown";
        case keyboard_key::k_end:
            return "k_end";
        case keyboard_key::k_home:
            return "k_home";
        case keyboard_key::k_left:
            return "k_left";
        case keyboard_key::k_up:
            return "k_up";
        case keyboard_key::k_right:
            return "k_right";
        case keyboard_key::k_down:
            return "k_down";
        case keyboard_key::k_print:
            return "k_print";
        case keyboard_key::k_print_screen:
            return "k_print_screen";
        case keyboard_key::k_insert:
            return "k_insert";
        case keyboard_key::k_delete:
            return "k_delete";
        case keyboard_key::k_help:
            return "k_help";
        case keyboard_key::k_0:
            return "k_0";
        case keyboard_key::k_1:
            return "k_1";
        case keyboard_key::k_2:
            return "k_2";
        case keyboard_key::k_3:
            return "k_3";
        case keyboard_key::k_4:
            return "k_4";
        case keyboard_key::k_5:
            return "k_5";
        case keyboard_key::k_6:
            return "k_6";
        case keyboard_key::k_7:
            return "k_7";
        case keyboard_key::k_8:
            return "k_8";
        case keyboard_key::k_9:
            return "k_9";
        case keyboard_key::k_A:
            return "k_A";
        case keyboard_key::k_B:
            return "k_B";
        case keyboard_key::k_C:
            return "k_C";
        case keyboard_key::k_D:
            return "k_D";
        case keyboard_key::k_E:
            return "k_E";
        case keyboard_key::k_F:
            return "k_F";
        case keyboard_key::k_G:
            return "k_G";
        case keyboard_key::k_H:
            return "k_H";
        case keyboard_key::k_I:
            return "k_I";
        case keyboard_key::k_J:
            return "k_J";
        case keyboard_key::k_K:
            return "k_K";
        case keyboard_key::k_L:
            return "k_L";
        case keyboard_key::k_M:
            return "k_M";
        case keyboard_key::k_N:
            return "k_N";
        case keyboard_key::k_O:
            return "k_O";
        case keyboard_key::k_P:
            return "k_P";
        case keyboard_key::k_Q:
            return "k_Q";
        case keyboard_key::k_R:
            return "k_R";
        case keyboard_key::k_S:
            return "k_S";
        case keyboard_key::k_T:
            return "k_T";
        case keyboard_key::k_U:
            return "k_U";
        case keyboard_key::k_V:
            return "k_V";
        case keyboard_key::k_W:
            return "k_W";
        case keyboard_key::k_X:
            return "k_X";
        case keyboard_key::k_Y:
            return "k_Y";
        case keyboard_key::k_Z:
            return "k_Z";
        case keyboard_key::k_lsuper:
            return "k_lsuper";
        case keyboard_key::k_rsuper:
            return "k_rsuper";
        case keyboard_key::k_menu:
            return "k_menu";
        case keyboard_key::k_numpad0:
            return "k_numpad0";
        case keyboard_key::k_numpad1:
            return "k_numpad1";
        case keyboard_key::k_numpad2:
            return "k_numpad2";
        case keyboard_key::k_numpad3:
            return "k_numpad3";
        case keyboard_key::k_numpad4:
            return "k_numpad4";
        case keyboard_key::k_numpad5:
            return "k_numpad5";
        case keyboard_key::k_numpad6:
            return "k_numpad6";
        case keyboard_key::k_numpad7:
            return "k_numpad7";
        case keyboard_key::k_numpad8:
            return "k_numpad8";
        case keyboard_key::k_numpad9:
            return "k_numpad9";
        case keyboard_key::k_multiply:
            return "k_multiply";
        case keyboard_key::k_add:
            return "k_add";
        case keyboard_key::k_subtract:
            return "k_subtract";
        case keyboard_key::k_decimal:
            return "k_decimal";
        case keyboard_key::k_divide:
            return "k_divide";
        case keyboard_key::k_F1:
            return "k_F1";
        case keyboard_key::k_F2:
            return "k_F2";
        case keyboard_key::k_F3:
            return "k_F3";
        case keyboard_key::k_F4:
            return "k_F4";
        case keyboard_key::k_F5:
            return "k_F5";
        case keyboard_key::k_F6:
            return "k_F6";
        case keyboard_key::k_F7:
            return "k_F7";
        case keyboard_key::k_F8:
            return "k_F8";
        case keyboard_key::k_F9:
            return "k_F9";
        case keyboard_key::k_F10:
            return "k_F10";
        case keyboard_key::k_F11:
            return "k_F11";
        case keyboard_key::k_F12:
            return "k_F12";
        case keyboard_key::k_F13:
            return "k_F13";
        case keyboard_key::k_F14:
            return "k_F14";
        case keyboard_key::k_F15:
            return "k_F15";
        case keyboard_key::k_F16:
            return "k_F16";
        case keyboard_key::k_F17:
            return "k_F17";
        case keyboard_key::k_F18:
            return "k_F18";
        case keyboard_key::k_F19:
            return "k_F19";
        case keyboard_key::k_F20:
            return "k_F20";
        case keyboard_key::k_semicolon:
            return "k_semicolon";
        case keyboard_key::k_equal:
            return "k_equal";
        case keyboard_key::k_comma:
            return "k_comma";
        case keyboard_key::k_minus:
            return "k_minus";
        case keyboard_key::k_period:
            return "k_period";
        case keyboard_key::k_slash:
            return "k_slash";
        case keyboard_key::k_grave_accent:
            return "k_grave_accent";
        case keyboard_key::k_lbracket:
            return "k_lbracket";
        case keyboard_key::k_backslash:
            return "k_backslash";
        case keyboard_key::k_rbracket:
            return "k_rbracket";
        case keyboard_key::k_apostrophe:
            return "k_apostrophe";
        case keyboard_key::k_numlock:
            return "k_numlock";
        case keyboard_key::k_scroll:
            return "k_scroll";
        case keyboard_key::k_lshift:
            return "k_lshift";
        case keyboard_key::k_rshift:
            return "k_rshift";
        case keyboard_key::k_lcontrol:
            return "k_lcontrol";
        case keyboard_key::k_rcontrol:
            return "k_rcontrol";
        case keyboard_key::k_lalt:
            return "k_lalt";
        case keyboard_key::k_ralt:
            return "k_ralt";
        case keyboard_key::last_key:
            return "last_key";
        default:
            TAV_UNREACHABLE();
            return "<unknown>";
        }
    }

    core::string_view to_string(mouse_button btn) noexcept
    {
        switch (btn) {
        case mouse_button::none:
            return "none";
        case mouse_button::left:
            return "left";
        case mouse_button::right:
            return "right";
        case mouse_button::middle:
            return "middle";
        case mouse_button::x_button1:
            return "x_button1";
        case mouse_button::x_button2:
            return "x_button2";
        case mouse_button::last_button:
            return "last_button";
        default:
            TAV_UNREACHABLE();
            return "<unknown>";
        }
    }

} // namespace tavros::input
