/*
===========================================================================
Copyright (C) 1999-2005 Id Software, Inc.

This file is part of Quake III Arena source code.

Quake III Arena source code is free software; you can redistribute it
and/or modify it under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 2 of the License,
or (at your option) any later version.

Quake III Arena source code is distributed in the hope that it will be
useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Foobar; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
===========================================================================
*/
#include "tr_local.h"

#include <tavros/system/library.hpp>

static tavros::core::logger logger("qgl");

fn_glAccum_t                  qglAccum = NULL;
fn_glAlphaFunc_t              qglAlphaFunc = NULL;
fn_glArrayElement_t           qglArrayElement = NULL;
fn_glBegin_t                  qglBegin = NULL;
fn_glBindTexture_t            qglBindTexture = NULL;
fn_glBitmap_t                 qglBitmap = NULL;
fn_glBlendFunc_t              qglBlendFunc = NULL;
fn_glCallList_t               qglCallList = NULL;
fn_glCallLists_t              qglCallLists = NULL;
fn_glClear_t                  qglClear = NULL;
fn_glClearAccum_t             qglClearAccum = NULL;
fn_glClearColor_t             qglClearColor = NULL;
fn_glClearDepth_t             qglClearDepth = NULL;
fn_glClearIndex_t             qglClearIndex = NULL;
fn_glClearStencil_t           qglClearStencil = NULL;
fn_glClipPlane_t              qglClipPlane = NULL;
fn_glColor3b_t                qglColor3b = NULL;
fn_glColor3bv_t               qglColor3bv = NULL;
fn_glColor3d_t                qglColor3d = NULL;
fn_glColor3dv_t               qglColor3dv = NULL;
fn_glColor3f_t                qglColor3f = NULL;
fn_glColor3fv_t               qglColor3fv = NULL;
fn_glColor3i_t                qglColor3i = NULL;
fn_glColor3iv_t               qglColor3iv = NULL;
fn_glColor3s_t                qglColor3s = NULL;
fn_glColor3sv_t               qglColor3sv = NULL;
fn_glColor3ub_t               qglColor3ub = NULL;
fn_glColor3ubv_t              qglColor3ubv = NULL;
fn_glColor3ui_t               qglColor3ui = NULL;
fn_glColor3uiv_t              qglColor3uiv = NULL;
fn_glColor3us_t               qglColor3us = NULL;
fn_glColor3usv_t              qglColor3usv = NULL;
fn_glColor4b_t                qglColor4b = NULL;
fn_glColor4bv_t               qglColor4bv = NULL;
fn_glColor4d_t                qglColor4d = NULL;
fn_glColor4dv_t               qglColor4dv = NULL;
fn_glColor4f_t                qglColor4f = NULL;
fn_glColor4fv_t               qglColor4fv = NULL;
fn_glColor4i_t                qglColor4i = NULL;
fn_glColor4iv_t               qglColor4iv = NULL;
fn_glColor4s_t                qglColor4s = NULL;
fn_glColor4sv_t               qglColor4sv = NULL;
fn_glColor4ub_t               qglColor4ub = NULL;
fn_glColor4ubv_t              qglColor4ubv = NULL;
fn_glColor4ui_t               qglColor4ui = NULL;
fn_glColor4uiv_t              qglColor4uiv = NULL;
fn_glColor4us_t               qglColor4us = NULL;
fn_glColor4usv_t              qglColor4usv = NULL;
fn_glColorMask_t              qglColorMask = NULL;
fn_glColorMaterial_t          qglColorMaterial = NULL;
fn_glColorPointer_t           qglColorPointer = NULL;
fn_glCopyPixels_t             qglCopyPixels = NULL;
fn_glCopyTexImage1D_t         qglCopyTexImage1D = NULL;
fn_glCopyTexImage2D_t         qglCopyTexImage2D = NULL;
fn_glCopyTexSubImage1D_t      qglCopyTexSubImage1D = NULL;
fn_glCopyTexSubImage2D_t      qglCopyTexSubImage2D = NULL;
fn_glCullFace_t               qglCullFace = NULL;
fn_glDeleteLists_t            qglDeleteLists = NULL;
fn_glDeleteTextures_t         qglDeleteTextures = NULL;
fn_glDepthFunc_t              qglDepthFunc = NULL;
fn_glDepthMask_t              qglDepthMask = NULL;
fn_glDepthRange_t             qglDepthRange = NULL;
fn_glDisable_t                qglDisable = NULL;
fn_glDisableClientState_t     qglDisableClientState = NULL;
fn_glDrawArrays_t             qglDrawArrays = NULL;
fn_glDrawBuffer_t             qglDrawBuffer = NULL;
fn_glDrawElements_t           qglDrawElements = NULL;
fn_glDrawPixels_t             qglDrawPixels = NULL;
fn_glEdgeFlag_t               qglEdgeFlag = NULL;
fn_glEdgeFlagPointer_t        qglEdgeFlagPointer = NULL;
fn_glEdgeFlagv_t              qglEdgeFlagv = NULL;
fn_glEnable_t                 qglEnable = NULL;
fn_glEnableClientState_t      qglEnableClientState = NULL;
fn_glEnd_t                    qglEnd = NULL;
fn_glEndList_t                qglEndList = NULL;
fn_glEvalCoord1d_t            qglEvalCoord1d = NULL;
fn_glEvalCoord1dv_t           qglEvalCoord1dv = NULL;
fn_glEvalCoord1f_t            qglEvalCoord1f = NULL;
fn_glEvalCoord1fv_t           qglEvalCoord1fv = NULL;
fn_glEvalCoord2d_t            qglEvalCoord2d = NULL;
fn_glEvalCoord2dv_t           qglEvalCoord2dv = NULL;
fn_glEvalCoord2f_t            qglEvalCoord2f = NULL;
fn_glEvalCoord2fv_t           qglEvalCoord2fv = NULL;
fn_glEvalMesh1_t              qglEvalMesh1 = NULL;
fn_glEvalMesh2_t              qglEvalMesh2 = NULL;
fn_glEvalPoint1_t             qglEvalPoint1 = NULL;
fn_glEvalPoint2_t             qglEvalPoint2 = NULL;
fn_glFeedbackBuffer_t         qglFeedbackBuffer = NULL;
fn_glFinish_t                 qglFinish = NULL;
fn_glFlush_t                  qglFlush = NULL;
fn_glFogf_t                   qglFogf = NULL;
fn_glFogfv_t                  qglFogfv = NULL;
fn_glFogi_t                   qglFogi = NULL;
fn_glFogiv_t                  qglFogiv = NULL;
fn_glFrontFace_t              qglFrontFace = NULL;
fn_glFrustum_t                qglFrustum = NULL;
fn_glGenTextures_t            qglGenTextures = NULL;
fn_glGenerateMipmap_t         qglGenerateMipmap = NULL;
fn_glGetBooleanv_t            qglGetBooleanv = NULL;
fn_glGetClipPlane_t           qglGetClipPlane = NULL;
fn_glGetDoublev_t             qglGetDoublev = NULL;
fn_glGetError_t               qglGetError = NULL;
fn_glGetFloatv_t              qglGetFloatv = NULL;
fn_glGetIntegerv_t            qglGetIntegerv = NULL;
fn_glGetInteger_t             qglGetInteger = NULL;
fn_glGetLightfv_t             qglGetLightfv = NULL;
fn_glGetLightiv_t             qglGetLightiv = NULL;
fn_glGetMapdv_t               qglGetMapdv = NULL;
fn_glGetMapfv_t               qglGetMapfv = NULL;
fn_glGetMapiv_t               qglGetMapiv = NULL;
fn_glGetMaterialfv_t          qglGetMaterialfv = NULL;
fn_glGetMaterialiv_t          qglGetMaterialiv = NULL;
fn_glGetPixelMapfv_t          qglGetPixelMapfv = NULL;
fn_glGetPixelMapuiv_t         qglGetPixelMapuiv = NULL;
fn_glGetPixelMapusv_t         qglGetPixelMapusv = NULL;
fn_glGetPointerv_t            qglGetPointerv = NULL;
fn_glGetPolygonStipple_t      qglGetPolygonStipple = NULL;
fn_glGetString_t              qglGetString = NULL;
fn_glGetTexEnvfv_t            qglGetTexEnvfv = NULL;
fn_glGetTexEnviv_t            qglGetTexEnviv = NULL;
fn_glGetTexGendv_t            qglGetTexGendv = NULL;
fn_glGetTexGenfv_t            qglGetTexGenfv = NULL;
fn_glGetTexGeniv_t            qglGetTexGeniv = NULL;
fn_glGetTexImage_t            qglGetTexImage = NULL;
fn_glGetTexLevelParameterfv_t qglGetTexLevelParameterfv = NULL;
fn_glGetTexLevelParameteriv_t qglGetTexLevelParameteriv = NULL;
fn_glGetTexParameterfv_t      qglGetTexParameterfv = NULL;
fn_glGetTexParameteriv_t      qglGetTexParameteriv = NULL;
fn_glHint_t                   qglHint = NULL;
fn_glIndexMask_t              qglIndexMask = NULL;
fn_glIndexPointer_t           qglIndexPointer = NULL;
fn_glIndexd_t                 qglIndexd = NULL;
fn_glIndexdv_t                qglIndexdv = NULL;
fn_glIndexf_t                 qglIndexf = NULL;
fn_glIndexfv_t                qglIndexfv = NULL;
fn_glIndexi_t                 qglIndexi = NULL;
fn_glIndexiv_t                qglIndexiv = NULL;
fn_glIndexs_t                 qglIndexs = NULL;
fn_glIndexsv_t                qglIndexsv = NULL;
fn_glIndexub_t                qglIndexub = NULL;
fn_glIndexubv_t               qglIndexubv = NULL;
fn_glInitNames_t              qglInitNames = NULL;
fn_glInterleavedArrays_t      qglInterleavedArrays = NULL;
fn_glIsEnabled_t              qglIsEnabled = NULL;
fn_glIsList_t                 qglIsList = NULL;
fn_glIsTexture_t              qglIsTexture = NULL;
fn_glLightModelf_t            qglLightModelf = NULL;
fn_glLightModelfv_t           qglLightModelfv = NULL;
fn_glLightModeli_t            qglLightModeli = NULL;
fn_glLightModeliv_t           qglLightModeliv = NULL;
fn_glLightf_t                 qglLightf = NULL;
fn_glLightfv_t                qglLightfv = NULL;
fn_glLighti_t                 qglLighti = NULL;
fn_glLightiv_t                qglLightiv = NULL;
fn_glLineStipple_t            qglLineStipple = NULL;
fn_glLineWidth_t              qglLineWidth = NULL;
fn_glListBase_t               qglListBase = NULL;
fn_glLoadIdentity_t           qglLoadIdentity = NULL;
fn_glLoadMatrixd_t            qglLoadMatrixd = NULL;
fn_glLoadMatrixf_t            qglLoadMatrixf = NULL;
fn_glLoadName_t               qglLoadName = NULL;
fn_glLogicOp_t                qglLogicOp = NULL;
fn_glMap1d_t                  qglMap1d = NULL;
fn_glMap1f_t                  qglMap1f = NULL;
fn_glMap2d_t                  qglMap2d = NULL;
fn_glMap2f_t                  qglMap2f = NULL;
fn_glMapGrid1d_t              qglMapGrid1d = NULL;
fn_glMapGrid1f_t              qglMapGrid1f = NULL;
fn_glMapGrid2d_t              qglMapGrid2d = NULL;
fn_glMapGrid2f_t              qglMapGrid2f = NULL;
fn_glMaterialf_t              qglMaterialf = NULL;
fn_glMaterialfv_t             qglMaterialfv = NULL;
fn_glMateriali_t              qglMateriali = NULL;
fn_glMaterialiv_t             qglMaterialiv = NULL;
fn_glMatrixMode_t             qglMatrixMode = NULL;
fn_glMultMatrixd_t            qglMultMatrixd = NULL;
fn_glMultMatrixf_t            qglMultMatrixf = NULL;
fn_glNewList_t                qglNewList = NULL;
fn_glNormal3b_t               qglNormal3b = NULL;
fn_glNormal3bv_t              qglNormal3bv = NULL;
fn_glNormal3d_t               qglNormal3d = NULL;
fn_glNormal3dv_t              qglNormal3dv = NULL;
fn_glNormal3f_t               qglNormal3f = NULL;
fn_glNormal3fv_t              qglNormal3fv = NULL;
fn_glNormal3i_t               qglNormal3i = NULL;
fn_glNormal3iv_t              qglNormal3iv = NULL;
fn_glNormal3s_t               qglNormal3s = NULL;
fn_glNormal3sv_t              qglNormal3sv = NULL;
fn_glNormalPointer_t          qglNormalPointer = NULL;
fn_glOrtho_t                  qglOrtho = NULL;
fn_glPassThrough_t            qglPassThrough = NULL;
fn_glPixelMapfv_t             qglPixelMapfv = NULL;
fn_glPixelMapuiv_t            qglPixelMapuiv = NULL;
fn_glPixelMapusv_t            qglPixelMapusv = NULL;
fn_glPixelStoref_t            qglPixelStoref = NULL;
fn_glPixelStorei_t            qglPixelStorei = NULL;
fn_glPixelTransferf_t         qglPixelTransferf = NULL;
fn_glPixelTransferi_t         qglPixelTransferi = NULL;
fn_glPixelZoom_t              qglPixelZoom = NULL;
fn_glPointSize_t              qglPointSize = NULL;
fn_glPolygonMode_t            qglPolygonMode = NULL;
fn_glPolygonOffset_t          qglPolygonOffset = NULL;
fn_glPolygonStipple_t         qglPolygonStipple = NULL;
fn_glPopAttrib_t              qglPopAttrib = NULL;
fn_glPopClientAttrib_t        qglPopClientAttrib = NULL;
fn_glPopMatrix_t              qglPopMatrix = NULL;
fn_glPopName_t                qglPopName = NULL;
fn_glPrioritizeTextures_t     qglPrioritizeTextures = NULL;
fn_glPushAttrib_t             qglPushAttrib = NULL;
fn_glPushClientAttrib_t       qglPushClientAttrib = NULL;
fn_glPushMatrix_t             qglPushMatrix = NULL;
fn_glPushName_t               qglPushName = NULL;
fn_glRasterPos2d_t            qglRasterPos2d = NULL;
fn_glRasterPos2dv_t           qglRasterPos2dv = NULL;
fn_glRasterPos2f_t            qglRasterPos2f = NULL;
fn_glRasterPos2fv_t           qglRasterPos2fv = NULL;
fn_glRasterPos2i_t            qglRasterPos2i = NULL;
fn_glRasterPos2iv_t           qglRasterPos2iv = NULL;
fn_glRasterPos2s_t            qglRasterPos2s = NULL;
fn_glRasterPos2sv_t           qglRasterPos2sv = NULL;
fn_glRasterPos3d_t            qglRasterPos3d = NULL;
fn_glRasterPos3dv_t           qglRasterPos3dv = NULL;
fn_glRasterPos3f_t            qglRasterPos3f = NULL;
fn_glRasterPos3fv_t           qglRasterPos3fv = NULL;
fn_glRasterPos3i_t            qglRasterPos3i = NULL;
fn_glRasterPos3iv_t           qglRasterPos3iv = NULL;
fn_glRasterPos3s_t            qglRasterPos3s = NULL;
fn_glRasterPos3sv_t           qglRasterPos3sv = NULL;
fn_glRasterPos4d_t            qglRasterPos4d = NULL;
fn_glRasterPos4dv_t           qglRasterPos4dv = NULL;
fn_glRasterPos4f_t            qglRasterPos4f = NULL;
fn_glRasterPos4fv_t           qglRasterPos4fv = NULL;
fn_glRasterPos4i_t            qglRasterPos4i = NULL;
fn_glRasterPos4iv_t           qglRasterPos4iv = NULL;
fn_glRasterPos4s_t            qglRasterPos4s = NULL;
fn_glRasterPos4sv_t           qglRasterPos4sv = NULL;
fn_glReadBuffer_t             qglReadBuffer = NULL;
fn_glReadPixels_t             qglReadPixels = NULL;
fn_glRectd_t                  qglRectd = NULL;
fn_glRectdv_t                 qglRectdv = NULL;
fn_glRectf_t                  qglRectf = NULL;
fn_glRectfv_t                 qglRectfv = NULL;
fn_glRecti_t                  qglRecti = NULL;
fn_glRectiv_t                 qglRectiv = NULL;
fn_glRects_t                  qglRects = NULL;
fn_glRectsv_t                 qglRectsv = NULL;
fn_glRenderMode_t             qglRenderMode = NULL;
fn_glRotated_t                qglRotated = NULL;
fn_glRotatef_t                qglRotatef = NULL;
fn_glScaled_t                 qglScaled = NULL;
fn_glScalef_t                 qglScalef = NULL;
fn_glScissor_t                qglScissor = NULL;
fn_glSelectBuffer_t           qglSelectBuffer = NULL;
fn_glShadeModel_t             qglShadeModel = NULL;
fn_glStencilFunc_t            qglStencilFunc = NULL;
fn_glStencilMask_t            qglStencilMask = NULL;
fn_glStencilOp_t              qglStencilOp = NULL;
fn_glTexCoord1d_t             qglTexCoord1d = NULL;
fn_glTexCoord1dv_t            qglTexCoord1dv = NULL;
fn_glTexCoord1f_t             qglTexCoord1f = NULL;
fn_glTexCoord1fv_t            qglTexCoord1fv = NULL;
fn_glTexCoord1i_t             qglTexCoord1i = NULL;
fn_glTexCoord1iv_t            qglTexCoord1iv = NULL;
fn_glTexCoord1s_t             qglTexCoord1s = NULL;
fn_glTexCoord1sv_t            qglTexCoord1sv = NULL;
fn_glTexCoord2d_t             qglTexCoord2d = NULL;
fn_glTexCoord2dv_t            qglTexCoord2dv = NULL;
fn_glTexCoord2f_t             qglTexCoord2f = NULL;
fn_glTexCoord2fv_t            qglTexCoord2fv = NULL;
fn_glTexCoord2i_t             qglTexCoord2i = NULL;
fn_glTexCoord2iv_t            qglTexCoord2iv = NULL;
fn_glTexCoord2s_t             qglTexCoord2s = NULL;
fn_glTexCoord2sv_t            qglTexCoord2sv = NULL;
fn_glTexCoord3d_t             qglTexCoord3d = NULL;
fn_glTexCoord3dv_t            qglTexCoord3dv = NULL;
fn_glTexCoord3f_t             qglTexCoord3f = NULL;
fn_glTexCoord3fv_t            qglTexCoord3fv = NULL;
fn_glTexCoord3i_t             qglTexCoord3i = NULL;
fn_glTexCoord3iv_t            qglTexCoord3iv = NULL;
fn_glTexCoord3s_t             qglTexCoord3s = NULL;
fn_glTexCoord3sv_t            qglTexCoord3sv = NULL;
fn_glTexCoord4d_t             qglTexCoord4d = NULL;
fn_glTexCoord4dv_t            qglTexCoord4dv = NULL;
fn_glTexCoord4f_t             qglTexCoord4f = NULL;
fn_glTexCoord4fv_t            qglTexCoord4fv = NULL;
fn_glTexCoord4i_t             qglTexCoord4i = NULL;
fn_glTexCoord4iv_t            qglTexCoord4iv = NULL;
fn_glTexCoord4s_t             qglTexCoord4s = NULL;
fn_glTexCoord4sv_t            qglTexCoord4sv = NULL;
fn_glTexCoordPointer_t        qglTexCoordPointer = NULL;
fn_glTexEnvf_t                qglTexEnvf = NULL;
fn_glTexEnvfv_t               qglTexEnvfv = NULL;
fn_glTexEnvi_t                qglTexEnvi = NULL;
fn_glTexEnviv_t               qglTexEnviv = NULL;
fn_glTexGend_t                qglTexGend = NULL;
fn_glTexGendv_t               qglTexGendv = NULL;
fn_glTexGenf_t                qglTexGenf = NULL;
fn_glTexGenfv_t               qglTexGenfv = NULL;
fn_glTexGeni_t                qglTexGeni = NULL;
fn_glTexGeniv_t               qglTexGeniv = NULL;
fn_glTexImage1D_t             qglTexImage1D = NULL;
fn_glTexImage2D_t             qglTexImage2D = NULL;
fn_glTexParameterf_t          qglTexParameterf = NULL;
fn_glTexParameterfv_t         qglTexParameterfv = NULL;
fn_glTexParameteri_t          qglTexParameteri = NULL;
fn_glTexParameteriv_t         qglTexParameteriv = NULL;
fn_glTexSubImage1D_t          qglTexSubImage1D = NULL;
fn_glTexSubImage2D_t          qglTexSubImage2D = NULL;
fn_glTranslated_t             qglTranslated = NULL;
fn_glTranslatef_t             qglTranslatef = NULL;
fn_glVertex2d_t               qglVertex2d = NULL;
fn_glVertex2dv_t              qglVertex2dv = NULL;
fn_glVertex2f_t               qglVertex2f = NULL;
fn_glVertex2fv_t              qglVertex2fv = NULL;
fn_glVertex2i_t               qglVertex2i = NULL;
fn_glVertex2iv_t              qglVertex2iv = NULL;
fn_glVertex2s_t               qglVertex2s = NULL;
fn_glVertex2sv_t              qglVertex2sv = NULL;
fn_glVertex3d_t               qglVertex3d = NULL;
fn_glVertex3dv_t              qglVertex3dv = NULL;
fn_glVertex3f_t               qglVertex3f = NULL;
fn_glVertex3fv_t              qglVertex3fv = NULL;
fn_glVertex3i_t               qglVertex3i = NULL;
fn_glVertex3iv_t              qglVertex3iv = NULL;
fn_glVertex3s_t               qglVertex3s = NULL;
fn_glVertex3sv_t              qglVertex3sv = NULL;
fn_glVertex4d_t               qglVertex4d = NULL;
fn_glVertex4dv_t              qglVertex4dv = NULL;
fn_glVertex4f_t               qglVertex4f = NULL;
fn_glVertex4fv_t              qglVertex4fv = NULL;
fn_glVertex4i_t               qglVertex4i = NULL;
fn_glVertex4iv_t              qglVertex4iv = NULL;
fn_glVertex4s_t               qglVertex4s = NULL;
fn_glVertex4sv_t              qglVertex4sv = NULL;
fn_glVertexPointer_t          qglVertexPointer = NULL;
fn_glViewport_t               qglViewport = NULL;

/* impl_glGetInteger */
static GLint APIENTRY impl_glGetInteger(GLenum p)
{
    GLint ret = 0;
    qglGetIntegerv(p, &ret);
    return ret;
}

static tavros::system::library s_opengl_lib; // Instatnce to the OpenGL library.
typedef void*(APIENTRY* fn_wglGetProcAddress_t)(const char*);
static fn_wglGetProcAddress_t qwglGetProcAddress = nullptr;

/* GetGLLibProcAddress */
static void* GetGLLibProcAddress(const char* func_name)
{
    if (s_opengl_lib.is_open()) {
        void* func = s_opengl_lib.get_symbol(func_name);
        if (func == NULL) {
            logger.info("...GetGLLibProcAddress() failed: function '{}' was not found.", func_name);
        }
        return func;
    } else {
        logger.info("...GetGLLibProcAddress() failed: OpenGL library was not loaded.");
    }
    return NULL;
}

/* OpenGL_ShutdownLibrary */
static void OpenGL_ShutdownLibrary()
{
    if (s_opengl_lib.is_open()) {
        qwglGetProcAddress = NULL;

        logger.info("...unloading OpenGL DLL");
        s_opengl_lib.close();
    }
}

/* OpenGL_LoadLibrary */
static bool OpenGL_LoadLibrary()
{
    if (!s_opengl_lib.is_open()) {
        s_opengl_lib.open("opengl32");
        if (!s_opengl_lib.is_open()) {
            logger.error("Failed loading OpenGL library.");
            return false;
        } else {
            logger.info("OpenGL library loaded successfully.");
        }

        qwglGetProcAddress = (fn_wglGetProcAddress_t) GetGLLibProcAddress("wglGetProcAddress");

        if (qwglGetProcAddress == nullptr) {
            OpenGL_ShutdownLibrary();
            return false;
        }
    }
    return true;
}

static void* OpenGL_GetProcAddress(const char* func_name)
{
    void* func = NULL;
    if (qwglGetProcAddress != NULL) {
        func = qwglGetProcAddress(func_name);
    }
    if (func == NULL) {
        func = GetGLLibProcAddress(func_name);
    }
    if (func == NULL) {
        logger.info("...OpenGL_GetProcAddress() failed: function '{}' was not found.", func_name);
    }
    return func;
}

#define GPA(a) OpenGL_GetProcAddress(a)

/* OpenGL_Init
 *
 * This is responsible for binding OpenGL function pointers to the OpenGL library.
 * In Windows this means doing a LoadLibrary and a bunch of calls to GetProcAddress.
 * On other operating systems we need to do the right thing, whatever that might be.
 */
bool OpenGL_Init()
{
    logger.info("...initializing QpenGL");

    if (!OpenGL_LoadLibrary()) {
        return false;
    }

    qglAccum = (fn_glAccum_t) GPA("glAccum");
    qglAlphaFunc = (fn_glAlphaFunc_t) GPA("glAlphaFunc");
    qglArrayElement = (fn_glArrayElement_t) GPA("glArrayElement");
    qglBegin = (fn_glBegin_t) GPA("glBegin");
    qglBindTexture = (fn_glBindTexture_t) GPA("glBindTexture");
    qglBitmap = (fn_glBitmap_t) GPA("glBitmap");
    qglBlendFunc = (fn_glBlendFunc_t) GPA("glBlendFunc");
    qglCallList = (fn_glCallList_t) GPA("glCallList");
    qglCallLists = (fn_glCallLists_t) GPA("glCallLists");
    qglClear = (fn_glClear_t) GPA("glClear");
    qglClearAccum = (fn_glClearAccum_t) GPA("glClearAccum");
    qglClearColor = (fn_glClearColor_t) GPA("glClearColor");
    qglClearDepth = (fn_glClearDepth_t) GPA("glClearDepth");
    qglClearIndex = (fn_glClearIndex_t) GPA("glClearIndex");
    qglClearStencil = (fn_glClearStencil_t) GPA("glClearStencil");
    qglClipPlane = (fn_glClipPlane_t) GPA("glClipPlane");
    qglColor3b = (fn_glColor3b_t) GPA("glColor3b");
    qglColor3bv = (fn_glColor3bv_t) GPA("glColor3bv");
    qglColor3d = (fn_glColor3d_t) GPA("glColor3d");
    qglColor3dv = (fn_glColor3dv_t) GPA("glColor3dv");
    qglColor3f = (fn_glColor3f_t) GPA("glColor3f");
    qglColor3fv = (fn_glColor3fv_t) GPA("glColor3fv");
    qglColor3i = (fn_glColor3i_t) GPA("glColor3i");
    qglColor3iv = (fn_glColor3iv_t) GPA("glColor3iv");
    qglColor3s = (fn_glColor3s_t) GPA("glColor3s");
    qglColor3sv = (fn_glColor3sv_t) GPA("glColor3sv");
    qglColor3ub = (fn_glColor3ub_t) GPA("glColor3ub");
    qglColor3ubv = (fn_glColor3ubv_t) GPA("glColor3ubv");
    qglColor3ui = (fn_glColor3ui_t) GPA("glColor3ui");
    qglColor3uiv = (fn_glColor3uiv_t) GPA("glColor3uiv");
    qglColor3us = (fn_glColor3us_t) GPA("glColor3us");
    qglColor3usv = (fn_glColor3usv_t) GPA("glColor3usv");
    qglColor4b = (fn_glColor4b_t) GPA("glColor4b");
    qglColor4bv = (fn_glColor4bv_t) GPA("glColor4bv");
    qglColor4d = (fn_glColor4d_t) GPA("glColor4d");
    qglColor4dv = (fn_glColor4dv_t) GPA("glColor4dv");
    qglColor4f = (fn_glColor4f_t) GPA("glColor4f");
    qglColor4fv = (fn_glColor4fv_t) GPA("glColor4fv");
    qglColor4i = (fn_glColor4i_t) GPA("glColor4i");
    qglColor4iv = (fn_glColor4iv_t) GPA("glColor4iv");
    qglColor4s = (fn_glColor4s_t) GPA("glColor4s");
    qglColor4sv = (fn_glColor4sv_t) GPA("glColor4sv");
    qglColor4ub = (fn_glColor4ub_t) GPA("glColor4ub");
    qglColor4ubv = (fn_glColor4ubv_t) GPA("glColor4ubv");
    qglColor4ui = (fn_glColor4ui_t) GPA("glColor4ui");
    qglColor4uiv = (fn_glColor4uiv_t) GPA("glColor4uiv");
    qglColor4us = (fn_glColor4us_t) GPA("glColor4us");
    qglColor4usv = (fn_glColor4usv_t) GPA("glColor4usv");
    qglColorMask = (fn_glColorMask_t) GPA("glColorMask");
    qglColorMaterial = (fn_glColorMaterial_t) GPA("glColorMaterial");
    qglColorPointer = (fn_glColorPointer_t) GPA("glColorPointer");
    qglCopyPixels = (fn_glCopyPixels_t) GPA("glCopyPixels");
    qglCopyTexImage1D = (fn_glCopyTexImage1D_t) GPA("glCopyTexImage1D");
    qglCopyTexImage2D = (fn_glCopyTexImage2D_t) GPA("glCopyTexImage2D");
    qglCopyTexSubImage1D = (fn_glCopyTexSubImage1D_t) GPA("glCopyTexSubImage1D");
    qglCopyTexSubImage2D = (fn_glCopyTexSubImage2D_t) GPA("glCopyTexSubImage2D");
    qglCullFace = (fn_glCullFace_t) GPA("glCullFace");
    qglDeleteLists = (fn_glDeleteLists_t) GPA("glDeleteLists");
    qglDeleteTextures = (fn_glDeleteTextures_t) GPA("glDeleteTextures");
    qglDepthFunc = (fn_glDepthFunc_t) GPA("glDepthFunc");
    qglDepthMask = (fn_glDepthMask_t) GPA("glDepthMask");
    qglDepthRange = (fn_glDepthRange_t) GPA("glDepthRange");
    qglDisable = (fn_glDisable_t) GPA("glDisable");
    qglDisableClientState = (fn_glDisableClientState_t) GPA("glDisableClientState");
    qglDrawArrays = (fn_glDrawArrays_t) GPA("glDrawArrays");
    qglDrawBuffer = (fn_glDrawBuffer_t) GPA("glDrawBuffer");
    qglDrawElements = (fn_glDrawElements_t) GPA("glDrawElements");
    qglDrawPixels = (fn_glDrawPixels_t) GPA("glDrawPixels");
    qglEdgeFlag = (fn_glEdgeFlag_t) GPA("glEdgeFlag");
    qglEdgeFlagPointer = (fn_glEdgeFlagPointer_t) GPA("glEdgeFlagPointer");
    qglEdgeFlagv = (fn_glEdgeFlagv_t) GPA("glEdgeFlagv");
    qglEnable = (fn_glEnable_t) GPA("glEnable");
    qglEnableClientState = (fn_glEnableClientState_t) GPA("glEnableClientState");
    qglEnd = (fn_glEnd_t) GPA("glEnd");
    qglEndList = (fn_glEndList_t) GPA("glEndList");
    qglEvalCoord1d = (fn_glEvalCoord1d_t) GPA("glEvalCoord1d");
    qglEvalCoord1dv = (fn_glEvalCoord1dv_t) GPA("glEvalCoord1dv");
    qglEvalCoord1f = (fn_glEvalCoord1f_t) GPA("glEvalCoord1f");
    qglEvalCoord1fv = (fn_glEvalCoord1fv_t) GPA("glEvalCoord1fv");
    qglEvalCoord2d = (fn_glEvalCoord2d_t) GPA("glEvalCoord2d");
    qglEvalCoord2dv = (fn_glEvalCoord2dv_t) GPA("glEvalCoord2dv");
    qglEvalCoord2f = (fn_glEvalCoord2f_t) GPA("glEvalCoord2f");
    qglEvalCoord2fv = (fn_glEvalCoord2fv_t) GPA("glEvalCoord2fv");
    qglEvalMesh1 = (fn_glEvalMesh1_t) GPA("glEvalMesh1");
    qglEvalMesh2 = (fn_glEvalMesh2_t) GPA("glEvalMesh2");
    qglEvalPoint1 = (fn_glEvalPoint1_t) GPA("glEvalPoint1");
    qglEvalPoint2 = (fn_glEvalPoint2_t) GPA("glEvalPoint2");
    qglFeedbackBuffer = (fn_glFeedbackBuffer_t) GPA("glFeedbackBuffer");
    qglFinish = (fn_glFinish_t) GPA("glFinish");
    qglFlush = (fn_glFlush_t) GPA("glFlush");
    qglFogf = (fn_glFogf_t) GPA("glFogf");
    qglFogfv = (fn_glFogfv_t) GPA("glFogfv");
    qglFogi = (fn_glFogi_t) GPA("glFogi");
    qglFogiv = (fn_glFogiv_t) GPA("glFogiv");
    qglFrontFace = (fn_glFrontFace_t) GPA("glFrontFace");
    qglFrustum = (fn_glFrustum_t) GPA("glFrustum");
    qglGenTextures = (fn_glGenTextures_t) GPA("glGenTextures");
    qglGenerateMipmap = (fn_glGenerateMipmap_t) GPA("glGenerateMipmap");
    qglGetBooleanv = (fn_glGetBooleanv_t) GPA("glGetBooleanv");
    qglGetClipPlane = (fn_glGetClipPlane_t) GPA("glGetClipPlane");
    qglGetDoublev = (fn_glGetDoublev_t) GPA("glGetDoublev");
    qglGetError = (fn_glGetError_t) (GLenum(__stdcall*)()) GPA("glGetError");
    qglGetFloatv = (fn_glGetFloatv_t) GPA("glGetFloatv");
    qglGetIntegerv = (fn_glGetIntegerv_t) GPA("glGetIntegerv");
    qglGetInteger = (fn_glGetInteger_t) impl_glGetInteger;
    qglGetLightfv = (fn_glGetLightfv_t) GPA("glGetLightfv");
    qglGetLightiv = (fn_glGetLightiv_t) GPA("glGetLightiv");
    qglGetMapdv = (fn_glGetMapdv_t) GPA("glGetMapdv");
    qglGetMapfv = (fn_glGetMapfv_t) GPA("glGetMapfv");
    qglGetMapiv = (fn_glGetMapiv_t) GPA("glGetMapiv");
    qglGetMaterialfv = (fn_glGetMaterialfv_t) GPA("glGetMaterialfv");
    qglGetMaterialiv = (fn_glGetMaterialiv_t) GPA("glGetMaterialiv");
    qglGetPixelMapfv = (fn_glGetPixelMapfv_t) GPA("glGetPixelMapfv");
    qglGetPixelMapuiv = (fn_glGetPixelMapuiv_t) GPA("glGetPixelMapuiv");
    qglGetPixelMapusv = (fn_glGetPixelMapusv_t) GPA("glGetPixelMapusv");
    qglGetPointerv = (fn_glGetPointerv_t) GPA("glGetPointerv");
    qglGetPolygonStipple = (fn_glGetPolygonStipple_t) GPA("glGetPolygonStipple");
    qglGetString = (fn_glGetString_t) GPA("glGetString");
    qglGetTexEnvfv = (fn_glGetTexEnvfv_t) GPA("glGetTexEnvfv");
    qglGetTexEnviv = (fn_glGetTexEnviv_t) GPA("glGetTexEnviv");
    qglGetTexGendv = (fn_glGetTexGendv_t) GPA("glGetTexGendv");
    qglGetTexGenfv = (fn_glGetTexGenfv_t) GPA("glGetTexGenfv");
    qglGetTexGeniv = (fn_glGetTexGeniv_t) GPA("glGetTexGeniv");
    qglGetTexImage = (fn_glGetTexImage_t) GPA("glGetTexImage");
    qglGetTexParameterfv = (fn_glGetTexParameterfv_t) GPA("glGetTexParameterfv");
    qglGetTexParameteriv = (fn_glGetTexParameteriv_t) GPA("glGetTexParameteriv");
    qglHint = (fn_glHint_t) GPA("glHint");
    qglIndexMask = (fn_glIndexMask_t) GPA("glIndexMask");
    qglIndexPointer = (fn_glIndexPointer_t) GPA("glIndexPointer");
    qglIndexd = (fn_glIndexd_t) GPA("glIndexd");
    qglIndexdv = (fn_glIndexdv_t) GPA("glIndexdv");
    qglIndexf = (fn_glIndexf_t) GPA("glIndexf");
    qglIndexfv = (fn_glIndexfv_t) GPA("glIndexfv");
    qglIndexi = (fn_glIndexi_t) GPA("glIndexi");
    qglIndexiv = (fn_glIndexiv_t) GPA("glIndexiv");
    qglIndexs = (fn_glIndexs_t) GPA("glIndexs");
    qglIndexsv = (fn_glIndexsv_t) GPA("glIndexsv");
    qglIndexub = (fn_glIndexub_t) GPA("glIndexub");
    qglIndexubv = (fn_glIndexubv_t) GPA("glIndexubv");
    qglInitNames = (fn_glInitNames_t) GPA("glInitNames");
    qglInterleavedArrays = (fn_glInterleavedArrays_t) GPA("glInterleavedArrays");
    qglIsEnabled = (fn_glIsEnabled_t) GPA("glIsEnabled");
    qglIsList = (fn_glIsList_t) GPA("glIsList");
    qglIsTexture = (fn_glIsTexture_t) GPA("glIsTexture");
    qglLightModelf = (fn_glLightModelf_t) GPA("glLightModelf");
    qglLightModelfv = (fn_glLightModelfv_t) GPA("glLightModelfv");
    qglLightModeli = (fn_glLightModeli_t) GPA("glLightModeli");
    qglLightModeliv = (fn_glLightModeliv_t) GPA("glLightModeliv");
    qglLightf = (fn_glLightf_t) GPA("glLightf");
    qglLightfv = (fn_glLightfv_t) GPA("glLightfv");
    qglLighti = (fn_glLighti_t) GPA("glLighti");
    qglLightiv = (fn_glLightiv_t) GPA("glLightiv");
    qglLineStipple = (fn_glLineStipple_t) GPA("glLineStipple");
    qglLineWidth = (fn_glLineWidth_t) GPA("glLineWidth");
    qglListBase = (fn_glListBase_t) GPA("glListBase");
    qglLoadIdentity = (fn_glLoadIdentity_t) GPA("glLoadIdentity");
    qglLoadMatrixd = (fn_glLoadMatrixd_t) GPA("glLoadMatrixd");
    qglLoadMatrixf = (fn_glLoadMatrixf_t) GPA("glLoadMatrixf");
    qglLoadName = (fn_glLoadName_t) GPA("glLoadName");
    qglLogicOp = (fn_glLogicOp_t) GPA("glLogicOp");
    qglMap1d = (fn_glMap1d_t) GPA("glMap1d");
    qglMap1f = (fn_glMap1f_t) GPA("glMap1f");
    qglMap2d = (fn_glMap2d_t) GPA("glMap2d");
    qglMap2f = (fn_glMap2f_t) GPA("glMap2f");
    qglMapGrid1d = (fn_glMapGrid1d_t) GPA("glMapGrid1d");
    qglMapGrid1f = (fn_glMapGrid1f_t) GPA("glMapGrid1f");
    qglMapGrid2d = (fn_glMapGrid2d_t) GPA("glMapGrid2d");
    qglMapGrid2f = (fn_glMapGrid2f_t) GPA("glMapGrid2f");
    qglMaterialf = (fn_glMaterialf_t) GPA("glMaterialf");
    qglMaterialfv = (fn_glMaterialfv_t) GPA("glMaterialfv");
    qglMateriali = (fn_glMateriali_t) GPA("glMateriali");
    qglMaterialiv = (fn_glMaterialiv_t) GPA("glMaterialiv");
    qglMatrixMode = (fn_glMatrixMode_t) GPA("glMatrixMode");
    qglMultMatrixd = (fn_glMultMatrixd_t) GPA("glMultMatrixd");
    qglMultMatrixf = (fn_glMultMatrixf_t) GPA("glMultMatrixf");
    qglNewList = (fn_glNewList_t) GPA("glNewList");
    qglNormal3b = (fn_glNormal3b_t) GPA("glNormal3b");
    qglNormal3bv = (fn_glNormal3bv_t) GPA("glNormal3bv");
    qglNormal3d = (fn_glNormal3d_t) GPA("glNormal3d");
    qglNormal3dv = (fn_glNormal3dv_t) GPA("glNormal3dv");
    qglNormal3f = (fn_glNormal3f_t) GPA("glNormal3f");
    qglNormal3fv = (fn_glNormal3fv_t) GPA("glNormal3fv");
    qglNormal3i = (fn_glNormal3i_t) GPA("glNormal3i");
    qglNormal3iv = (fn_glNormal3iv_t) GPA("glNormal3iv");
    qglNormal3s = (fn_glNormal3s_t) GPA("glNormal3s");
    qglNormal3sv = (fn_glNormal3sv_t) GPA("glNormal3sv");
    qglNormalPointer = (fn_glNormalPointer_t) GPA("glNormalPointer");
    qglOrtho = (fn_glOrtho_t) GPA("glOrtho");
    qglPassThrough = (fn_glPassThrough_t) GPA("glPassThrough");
    qglPixelMapfv = (fn_glPixelMapfv_t) GPA("glPixelMapfv");
    qglPixelMapuiv = (fn_glPixelMapuiv_t) GPA("glPixelMapuiv");
    qglPixelMapusv = (fn_glPixelMapusv_t) GPA("glPixelMapusv");
    qglPixelStoref = (fn_glPixelStoref_t) GPA("glPixelStoref");
    qglPixelStorei = (fn_glPixelStorei_t) GPA("glPixelStorei");
    qglPixelTransferf = (fn_glPixelTransferf_t) GPA("glPixelTransferf");
    qglPixelTransferi = (fn_glPixelTransferi_t) GPA("glPixelTransferi");
    qglPixelZoom = (fn_glPixelZoom_t) GPA("glPixelZoom");
    qglPointSize = (fn_glPointSize_t) GPA("glPointSize");
    qglPolygonMode = (fn_glPolygonMode_t) GPA("glPolygonMode");
    qglPolygonOffset = (fn_glPolygonOffset_t) GPA("glPolygonOffset");
    qglPolygonStipple = (fn_glPolygonStipple_t) GPA("glPolygonStipple");
    qglPopAttrib = (fn_glPopAttrib_t) GPA("glPopAttrib");
    qglPopClientAttrib = (fn_glPopClientAttrib_t) GPA("glPopClientAttrib");
    qglPopMatrix = (fn_glPopMatrix_t) GPA("glPopMatrix");
    qglPopName = (fn_glPopName_t) GPA("glPopName");
    qglPrioritizeTextures = (fn_glPrioritizeTextures_t) GPA("glPrioritizeTextures");
    qglPushAttrib = (fn_glPushAttrib_t) GPA("glPushAttrib");
    qglPushClientAttrib = (fn_glPushClientAttrib_t) GPA("glPushClientAttrib");
    qglPushMatrix = (fn_glPushMatrix_t) GPA("glPushMatrix");
    qglPushName = (fn_glPushName_t) GPA("glPushName");
    qglRasterPos2d = (fn_glRasterPos2d_t) GPA("glRasterPos2d");
    qglRasterPos2dv = (fn_glRasterPos2dv_t) GPA("glRasterPos2dv");
    qglRasterPos2f = (fn_glRasterPos2f_t) GPA("glRasterPos2f");
    qglRasterPos2fv = (fn_glRasterPos2fv_t) GPA("glRasterPos2fv");
    qglRasterPos2i = (fn_glRasterPos2i_t) GPA("glRasterPos2i");
    qglRasterPos2iv = (fn_glRasterPos2iv_t) GPA("glRasterPos2iv");
    qglRasterPos2s = (fn_glRasterPos2s_t) GPA("glRasterPos2s");
    qglRasterPos2sv = (fn_glRasterPos2sv_t) GPA("glRasterPos2sv");
    qglRasterPos3d = (fn_glRasterPos3d_t) GPA("glRasterPos3d");
    qglRasterPos3dv = (fn_glRasterPos3dv_t) GPA("glRasterPos3dv");
    qglRasterPos3f = (fn_glRasterPos3f_t) GPA("glRasterPos3f");
    qglRasterPos3fv = (fn_glRasterPos3fv_t) GPA("glRasterPos3fv");
    qglRasterPos3i = (fn_glRasterPos3i_t) GPA("glRasterPos3i");
    qglRasterPos3iv = (fn_glRasterPos3iv_t) GPA("glRasterPos3iv");
    qglRasterPos3s = (fn_glRasterPos3s_t) GPA("glRasterPos3s");
    qglRasterPos3sv = (fn_glRasterPos3sv_t) GPA("glRasterPos3sv");
    qglRasterPos4d = (fn_glRasterPos4d_t) GPA("glRasterPos4d");
    qglRasterPos4dv = (fn_glRasterPos4dv_t) GPA("glRasterPos4dv");
    qglRasterPos4f = (fn_glRasterPos4f_t) GPA("glRasterPos4f");
    qglRasterPos4fv = (fn_glRasterPos4fv_t) GPA("glRasterPos4fv");
    qglRasterPos4i = (fn_glRasterPos4i_t) GPA("glRasterPos4i");
    qglRasterPos4iv = (fn_glRasterPos4iv_t) GPA("glRasterPos4iv");
    qglRasterPos4s = (fn_glRasterPos4s_t) GPA("glRasterPos4s");
    qglRasterPos4sv = (fn_glRasterPos4sv_t) GPA("glRasterPos4sv");
    qglReadBuffer = (fn_glReadBuffer_t) GPA("glReadBuffer");
    qglReadPixels = (fn_glReadPixels_t) GPA("glReadPixels");
    qglRectd = (fn_glRectd_t) GPA("glRectd");
    qglRectdv = (fn_glRectdv_t) GPA("glRectdv");
    qglRectf = (fn_glRectf_t) GPA("glRectf");
    qglRectfv = (fn_glRectfv_t) GPA("glRectfv");
    qglRecti = (fn_glRecti_t) GPA("glRecti");
    qglRectiv = (fn_glRectiv_t) GPA("glRectiv");
    qglRects = (fn_glRects_t) GPA("glRects");
    qglRectsv = (fn_glRectsv_t) GPA("glRectsv");
    qglRenderMode = (fn_glRenderMode_t) GPA("glRenderMode");
    qglRotated = (fn_glRotated_t) GPA("glRotated");
    qglRotatef = (fn_glRotatef_t) GPA("glRotatef");
    qglScaled = (fn_glScaled_t) GPA("glScaled");
    qglScalef = (fn_glScalef_t) GPA("glScalef");
    qglScissor = (fn_glScissor_t) GPA("glScissor");
    qglSelectBuffer = (fn_glSelectBuffer_t) GPA("glSelectBuffer");
    qglShadeModel = (fn_glShadeModel_t) GPA("glShadeModel");
    qglStencilFunc = (fn_glStencilFunc_t) GPA("glStencilFunc");
    qglStencilMask = (fn_glStencilMask_t) GPA("glStencilMask");
    qglStencilOp = (fn_glStencilOp_t) GPA("glStencilOp");
    qglTexCoord1d = (fn_glTexCoord1d_t) GPA("glTexCoord1d");
    qglTexCoord1dv = (fn_glTexCoord1dv_t) GPA("glTexCoord1dv");
    qglTexCoord1f = (fn_glTexCoord1f_t) GPA("glTexCoord1f");
    qglTexCoord1fv = (fn_glTexCoord1fv_t) GPA("glTexCoord1fv");
    qglTexCoord1i = (fn_glTexCoord1i_t) GPA("glTexCoord1i");
    qglTexCoord1iv = (fn_glTexCoord1iv_t) GPA("glTexCoord1iv");
    qglTexCoord1s = (fn_glTexCoord1s_t) GPA("glTexCoord1s");
    qglTexCoord1sv = (fn_glTexCoord1sv_t) GPA("glTexCoord1sv");
    qglTexCoord2d = (fn_glTexCoord2d_t) GPA("glTexCoord2d");
    qglTexCoord2dv = (fn_glTexCoord2dv_t) GPA("glTexCoord2dv");
    qglTexCoord2f = (fn_glTexCoord2f_t) GPA("glTexCoord2f");
    qglTexCoord2fv = (fn_glTexCoord2fv_t) GPA("glTexCoord2fv");
    qglTexCoord2i = (fn_glTexCoord2i_t) GPA("glTexCoord2i");
    qglTexCoord2iv = (fn_glTexCoord2iv_t) GPA("glTexCoord2iv");
    qglTexCoord2s = (fn_glTexCoord2s_t) GPA("glTexCoord2s");
    qglTexCoord2sv = (fn_glTexCoord2sv_t) GPA("glTexCoord2sv");
    qglTexCoord3d = (fn_glTexCoord3d_t) GPA("glTexCoord3d");
    qglTexCoord3dv = (fn_glTexCoord3dv_t) GPA("glTexCoord3dv");
    qglTexCoord3f = (fn_glTexCoord3f_t) GPA("glTexCoord3f");
    qglTexCoord3fv = (fn_glTexCoord3fv_t) GPA("glTexCoord3fv");
    qglTexCoord3i = (fn_glTexCoord3i_t) GPA("glTexCoord3i");
    qglTexCoord3iv = (fn_glTexCoord3iv_t) GPA("glTexCoord3iv");
    qglTexCoord3s = (fn_glTexCoord3s_t) GPA("glTexCoord3s");
    qglTexCoord3sv = (fn_glTexCoord3sv_t) GPA("glTexCoord3sv");
    qglTexCoord4d = (fn_glTexCoord4d_t) GPA("glTexCoord4d");
    qglTexCoord4dv = (fn_glTexCoord4dv_t) GPA("glTexCoord4dv");
    qglTexCoord4f = (fn_glTexCoord4f_t) GPA("glTexCoord4f");
    qglTexCoord4fv = (fn_glTexCoord4fv_t) GPA("glTexCoord4fv");
    qglTexCoord4i = (fn_glTexCoord4i_t) GPA("glTexCoord4i");
    qglTexCoord4iv = (fn_glTexCoord4iv_t) GPA("glTexCoord4iv");
    qglTexCoord4s = (fn_glTexCoord4s_t) GPA("glTexCoord4s");
    qglTexCoord4sv = (fn_glTexCoord4sv_t) GPA("glTexCoord4sv");
    qglTexCoordPointer = (fn_glTexCoordPointer_t) GPA("glTexCoordPointer");
    qglTexEnvf = (fn_glTexEnvf_t) GPA("glTexEnvf");
    qglTexEnvfv = (fn_glTexEnvfv_t) GPA("glTexEnvfv");
    qglTexEnvi = (fn_glTexEnvi_t) GPA("glTexEnvi");
    qglTexEnviv = (fn_glTexEnviv_t) GPA("glTexEnviv");
    qglTexGend = (fn_glTexGend_t) GPA("glTexGend");
    qglTexGendv = (fn_glTexGendv_t) GPA("glTexGendv");
    qglTexGenf = (fn_glTexGenf_t) GPA("glTexGenf");
    qglTexGenfv = (fn_glTexGenfv_t) GPA("glTexGenfv");
    qglTexGeni = (fn_glTexGeni_t) GPA("glTexGeni");
    qglTexGeniv = (fn_glTexGeniv_t) GPA("glTexGeniv");
    qglTexImage1D = (fn_glTexImage1D_t) GPA("glTexImage1D");
    qglTexImage2D = (fn_glTexImage2D_t) GPA("glTexImage2D");
    qglTexParameterf = (fn_glTexParameterf_t) GPA("glTexParameterf");
    qglTexParameterfv = (fn_glTexParameterfv_t) GPA("glTexParameterfv");
    qglTexParameteri = (fn_glTexParameteri_t) GPA("glTexParameteri");
    qglTexParameteriv = (fn_glTexParameteriv_t) GPA("glTexParameteriv");
    qglTexSubImage1D = (fn_glTexSubImage1D_t) GPA("glTexSubImage1D");
    qglTexSubImage2D = (fn_glTexSubImage2D_t) GPA("glTexSubImage2D");
    qglTranslated = (fn_glTranslated_t) GPA("glTranslated");
    qglTranslatef = (fn_glTranslatef_t) GPA("glTranslatef");
    qglVertex2d = (fn_glVertex2d_t) GPA("glVertex2d");
    qglVertex2dv = (fn_glVertex2dv_t) GPA("glVertex2dv");
    qglVertex2f = (fn_glVertex2f_t) GPA("glVertex2f");
    qglVertex2fv = (fn_glVertex2fv_t) GPA("glVertex2fv");
    qglVertex2i = (fn_glVertex2i_t) GPA("glVertex2i");
    qglVertex2iv = (fn_glVertex2iv_t) GPA("glVertex2iv");
    qglVertex2s = (fn_glVertex2s_t) GPA("glVertex2s");
    qglVertex2sv = (fn_glVertex2sv_t) GPA("glVertex2sv");
    qglVertex3d = (fn_glVertex3d_t) GPA("glVertex3d");
    qglVertex3dv = (fn_glVertex3dv_t) GPA("glVertex3dv");
    qglVertex3f = (fn_glVertex3f_t) GPA("glVertex3f");
    qglVertex3fv = (fn_glVertex3fv_t) GPA("glVertex3fv");
    qglVertex3i = (fn_glVertex3i_t) GPA("glVertex3i");
    qglVertex3iv = (fn_glVertex3iv_t) GPA("glVertex3iv");
    qglVertex3s = (fn_glVertex3s_t) GPA("glVertex3s");
    qglVertex3sv = (fn_glVertex3sv_t) GPA("glVertex3sv");
    qglVertex4d = (fn_glVertex4d_t) GPA("glVertex4d");
    qglVertex4dv = (fn_glVertex4dv_t) GPA("glVertex4dv");
    qglVertex4f = (fn_glVertex4f_t) GPA("glVertex4f");
    qglVertex4fv = (fn_glVertex4fv_t) GPA("glVertex4fv");
    qglVertex4i = (fn_glVertex4i_t) GPA("glVertex4i");
    qglVertex4iv = (fn_glVertex4iv_t) GPA("glVertex4iv");
    qglVertex4s = (fn_glVertex4s_t) GPA("glVertex4s");
    qglVertex4sv = (fn_glVertex4sv_t) GPA("glVertex4sv");
    qglVertexPointer = (fn_glVertexPointer_t) GPA("glVertexPointer");
    qglViewport = (fn_glViewport_t) GPA("glViewport");

    return true;
}

/* OpenGL_Shutdown
 *
 * Unloads the specified DLL then nulls out all the proc pointers. This is only called
 * during a hard shutdown of the OpenGL subsystem.
 */
void OpenGL_Shutdown()
{
    logger.info("...shutting down OpenGL");

    OpenGL_ShutdownLibrary();

    qglAccum = NULL;
    qglAlphaFunc = NULL;
    qglArrayElement = NULL;
    qglBegin = NULL;
    qglBindTexture = NULL;
    qglBitmap = NULL;
    qglBlendFunc = NULL;
    qglCallList = NULL;
    qglCallLists = NULL;
    qglClear = NULL;
    qglClearAccum = NULL;
    qglClearColor = NULL;
    qglClearDepth = NULL;
    qglClearIndex = NULL;
    qglClearStencil = NULL;
    qglClipPlane = NULL;
    qglColor3b = NULL;
    qglColor3bv = NULL;
    qglColor3d = NULL;
    qglColor3dv = NULL;
    qglColor3f = NULL;
    qglColor3fv = NULL;
    qglColor3i = NULL;
    qglColor3iv = NULL;
    qglColor3s = NULL;
    qglColor3sv = NULL;
    qglColor3ub = NULL;
    qglColor3ubv = NULL;
    qglColor3ui = NULL;
    qglColor3uiv = NULL;
    qglColor3us = NULL;
    qglColor3usv = NULL;
    qglColor4b = NULL;
    qglColor4bv = NULL;
    qglColor4d = NULL;
    qglColor4dv = NULL;
    qglColor4f = NULL;
    qglColor4fv = NULL;
    qglColor4i = NULL;
    qglColor4iv = NULL;
    qglColor4s = NULL;
    qglColor4sv = NULL;
    qglColor4ub = NULL;
    qglColor4ubv = NULL;
    qglColor4ui = NULL;
    qglColor4uiv = NULL;
    qglColor4us = NULL;
    qglColor4usv = NULL;
    qglColorMask = NULL;
    qglColorMaterial = NULL;
    qglColorPointer = NULL;
    qglCopyPixels = NULL;
    qglCopyTexImage1D = NULL;
    qglCopyTexImage2D = NULL;
    qglCopyTexSubImage1D = NULL;
    qglCopyTexSubImage2D = NULL;
    qglCullFace = NULL;
    qglDeleteLists = NULL;
    qglDeleteTextures = NULL;
    qglDepthFunc = NULL;
    qglDepthMask = NULL;
    qglDepthRange = NULL;
    qglDisable = NULL;
    qglDisableClientState = NULL;
    qglDrawArrays = NULL;
    qglDrawBuffer = NULL;
    qglDrawElements = NULL;
    qglDrawPixels = NULL;
    qglEdgeFlag = NULL;
    qglEdgeFlagPointer = NULL;
    qglEdgeFlagv = NULL;
    qglEnable = NULL;
    qglEnableClientState = NULL;
    qglEnd = NULL;
    qglEndList = NULL;
    qglEvalCoord1d = NULL;
    qglEvalCoord1dv = NULL;
    qglEvalCoord1f = NULL;
    qglEvalCoord1fv = NULL;
    qglEvalCoord2d = NULL;
    qglEvalCoord2dv = NULL;
    qglEvalCoord2f = NULL;
    qglEvalCoord2fv = NULL;
    qglEvalMesh1 = NULL;
    qglEvalMesh2 = NULL;
    qglEvalPoint1 = NULL;
    qglEvalPoint2 = NULL;
    qglFeedbackBuffer = NULL;
    qglFinish = NULL;
    qglFlush = NULL;
    qglFogf = NULL;
    qglFogfv = NULL;
    qglFogi = NULL;
    qglFogiv = NULL;
    qglFrontFace = NULL;
    qglFrustum = NULL;
    qglGenTextures = NULL;
    qglGenerateMipmap = NULL;
    qglGetBooleanv = NULL;
    qglGetClipPlane = NULL;
    qglGetDoublev = NULL;
    qglGetError = NULL;
    qglGetFloatv = NULL;
    qglGetIntegerv = NULL;
    qglGetInteger = NULL;
    qglGetLightfv = NULL;
    qglGetLightiv = NULL;
    qglGetMapdv = NULL;
    qglGetMapfv = NULL;
    qglGetMapiv = NULL;
    qglGetMaterialfv = NULL;
    qglGetMaterialiv = NULL;
    qglGetPixelMapfv = NULL;
    qglGetPixelMapuiv = NULL;
    qglGetPixelMapusv = NULL;
    qglGetPointerv = NULL;
    qglGetPolygonStipple = NULL;
    qglGetString = NULL;
    qglGetTexEnvfv = NULL;
    qglGetTexEnviv = NULL;
    qglGetTexGendv = NULL;
    qglGetTexGenfv = NULL;
    qglGetTexGeniv = NULL;
    qglGetTexImage = NULL;
    qglGetTexLevelParameterfv = NULL;
    qglGetTexLevelParameteriv = NULL;
    qglGetTexParameterfv = NULL;
    qglGetTexParameteriv = NULL;
    qglHint = NULL;
    qglIndexMask = NULL;
    qglIndexPointer = NULL;
    qglIndexd = NULL;
    qglIndexdv = NULL;
    qglIndexf = NULL;
    qglIndexfv = NULL;
    qglIndexi = NULL;
    qglIndexiv = NULL;
    qglIndexs = NULL;
    qglIndexsv = NULL;
    qglIndexub = NULL;
    qglIndexubv = NULL;
    qglInitNames = NULL;
    qglInterleavedArrays = NULL;
    qglIsEnabled = NULL;
    qglIsList = NULL;
    qglIsTexture = NULL;
    qglLightModelf = NULL;
    qglLightModelfv = NULL;
    qglLightModeli = NULL;
    qglLightModeliv = NULL;
    qglLightf = NULL;
    qglLightfv = NULL;
    qglLighti = NULL;
    qglLightiv = NULL;
    qglLineStipple = NULL;
    qglLineWidth = NULL;
    qglListBase = NULL;
    qglLoadIdentity = NULL;
    qglLoadMatrixd = NULL;
    qglLoadMatrixf = NULL;
    qglLoadName = NULL;
    qglLogicOp = NULL;
    qglMap1d = NULL;
    qglMap1f = NULL;
    qglMap2d = NULL;
    qglMap2f = NULL;
    qglMapGrid1d = NULL;
    qglMapGrid1f = NULL;
    qglMapGrid2d = NULL;
    qglMapGrid2f = NULL;
    qglMaterialf = NULL;
    qglMaterialfv = NULL;
    qglMateriali = NULL;
    qglMaterialiv = NULL;
    qglMatrixMode = NULL;
    qglMultMatrixd = NULL;
    qglMultMatrixf = NULL;
    qglNewList = NULL;
    qglNormal3b = NULL;
    qglNormal3bv = NULL;
    qglNormal3d = NULL;
    qglNormal3dv = NULL;
    qglNormal3f = NULL;
    qglNormal3fv = NULL;
    qglNormal3i = NULL;
    qglNormal3iv = NULL;
    qglNormal3s = NULL;
    qglNormal3sv = NULL;
    qglNormalPointer = NULL;
    qglOrtho = NULL;
    qglPassThrough = NULL;
    qglPixelMapfv = NULL;
    qglPixelMapuiv = NULL;
    qglPixelMapusv = NULL;
    qglPixelStoref = NULL;
    qglPixelStorei = NULL;
    qglPixelTransferf = NULL;
    qglPixelTransferi = NULL;
    qglPixelZoom = NULL;
    qglPointSize = NULL;
    qglPolygonMode = NULL;
    qglPolygonOffset = NULL;
    qglPolygonStipple = NULL;
    qglPopAttrib = NULL;
    qglPopClientAttrib = NULL;
    qglPopMatrix = NULL;
    qglPopName = NULL;
    qglPrioritizeTextures = NULL;
    qglPushAttrib = NULL;
    qglPushClientAttrib = NULL;
    qglPushMatrix = NULL;
    qglPushName = NULL;
    qglRasterPos2d = NULL;
    qglRasterPos2dv = NULL;
    qglRasterPos2f = NULL;
    qglRasterPos2fv = NULL;
    qglRasterPos2i = NULL;
    qglRasterPos2iv = NULL;
    qglRasterPos2s = NULL;
    qglRasterPos2sv = NULL;
    qglRasterPos3d = NULL;
    qglRasterPos3dv = NULL;
    qglRasterPos3f = NULL;
    qglRasterPos3fv = NULL;
    qglRasterPos3i = NULL;
    qglRasterPos3iv = NULL;
    qglRasterPos3s = NULL;
    qglRasterPos3sv = NULL;
    qglRasterPos4d = NULL;
    qglRasterPos4dv = NULL;
    qglRasterPos4f = NULL;
    qglRasterPos4fv = NULL;
    qglRasterPos4i = NULL;
    qglRasterPos4iv = NULL;
    qglRasterPos4s = NULL;
    qglRasterPos4sv = NULL;
    qglReadBuffer = NULL;
    qglReadPixels = NULL;
    qglRectd = NULL;
    qglRectdv = NULL;
    qglRectf = NULL;
    qglRectfv = NULL;
    qglRecti = NULL;
    qglRectiv = NULL;
    qglRects = NULL;
    qglRectsv = NULL;
    qglRenderMode = NULL;
    qglRotated = NULL;
    qglRotatef = NULL;
    qglScaled = NULL;
    qglScalef = NULL;
    qglScissor = NULL;
    qglSelectBuffer = NULL;
    qglShadeModel = NULL;
    qglStencilFunc = NULL;
    qglStencilMask = NULL;
    qglStencilOp = NULL;
    qglTexCoord1d = NULL;
    qglTexCoord1dv = NULL;
    qglTexCoord1f = NULL;
    qglTexCoord1fv = NULL;
    qglTexCoord1i = NULL;
    qglTexCoord1iv = NULL;
    qglTexCoord1s = NULL;
    qglTexCoord1sv = NULL;
    qglTexCoord2d = NULL;
    qglTexCoord2dv = NULL;
    qglTexCoord2f = NULL;
    qglTexCoord2fv = NULL;
    qglTexCoord2i = NULL;
    qglTexCoord2iv = NULL;
    qglTexCoord2s = NULL;
    qglTexCoord2sv = NULL;
    qglTexCoord3d = NULL;
    qglTexCoord3dv = NULL;
    qglTexCoord3f = NULL;
    qglTexCoord3fv = NULL;
    qglTexCoord3i = NULL;
    qglTexCoord3iv = NULL;
    qglTexCoord3s = NULL;
    qglTexCoord3sv = NULL;
    qglTexCoord4d = NULL;
    qglTexCoord4dv = NULL;
    qglTexCoord4f = NULL;
    qglTexCoord4fv = NULL;
    qglTexCoord4i = NULL;
    qglTexCoord4iv = NULL;
    qglTexCoord4s = NULL;
    qglTexCoord4sv = NULL;
    qglTexCoordPointer = NULL;
    qglTexEnvf = NULL;
    qglTexEnvfv = NULL;
    qglTexEnvi = NULL;
    qglTexEnviv = NULL;
    qglTexGend = NULL;
    qglTexGendv = NULL;
    qglTexGenf = NULL;
    qglTexGenfv = NULL;
    qglTexGeni = NULL;
    qglTexGeniv = NULL;
    qglTexImage1D = NULL;
    qglTexImage2D = NULL;
    qglTexParameterf = NULL;
    qglTexParameterfv = NULL;
    qglTexParameteri = NULL;
    qglTexParameteriv = NULL;
    qglTexSubImage1D = NULL;
    qglTexSubImage2D = NULL;
    qglTranslated = NULL;
    qglTranslatef = NULL;
    qglVertex2d = NULL;
    qglVertex2dv = NULL;
    qglVertex2f = NULL;
    qglVertex2fv = NULL;
    qglVertex2i = NULL;
    qglVertex2iv = NULL;
    qglVertex2s = NULL;
    qglVertex2sv = NULL;
    qglVertex3d = NULL;
    qglVertex3dv = NULL;
    qglVertex3f = NULL;
    qglVertex3fv = NULL;
    qglVertex3i = NULL;
    qglVertex3iv = NULL;
    qglVertex3s = NULL;
    qglVertex3sv = NULL;
    qglVertex4d = NULL;
    qglVertex4dv = NULL;
    qglVertex4f = NULL;
    qglVertex4fv = NULL;
    qglVertex4i = NULL;
    qglVertex4iv = NULL;
    qglVertex4s = NULL;
    qglVertex4sv = NULL;
    qglVertexPointer = NULL;
    qglViewport = NULL;
}
