#include <tavros/system/keys.hpp>

tavros::core::string_view tavros::system::to_string(keys k) noexcept
{
    switch (k) {
    case tavros::system::keys::none:
        return "none";
    case tavros::system::keys::k_lbutton:
        return "k_lbutton";
    case tavros::system::keys::k_rbutton:
        return "k_rbutton";
    case tavros::system::keys::k_break:
        return "k_break";
    case tavros::system::keys::k_mbutton:
        return "k_mbutton";
    case tavros::system::keys::k_xbutton1:
        return "k_xbutton1";
    case tavros::system::keys::k_xbutton2:
        return "k_xbutton2";
    case tavros::system::keys::k_backspace:
        return "k_backspace";
    case tavros::system::keys::k_tab:
        return "k_tab";
    case tavros::system::keys::k_enter:
        return "k_enter";
    case tavros::system::keys::k_pause:
        return "k_pause";
    case tavros::system::keys::k_capslock:
        return "k_capslock";
    case tavros::system::keys::k_escape:
        return "k_escape";
    case tavros::system::keys::k_space:
        return "k_space";
    case tavros::system::keys::k_pageup:
        return "k_pageup";
    case tavros::system::keys::k_pagedown:
        return "k_pagedown";
    case tavros::system::keys::k_end:
        return "k_end";
    case tavros::system::keys::k_home:
        return "k_home";
    case tavros::system::keys::k_left:
        return "k_left";
    case tavros::system::keys::k_up:
        return "k_up";
    case tavros::system::keys::k_right:
        return "k_right";
    case tavros::system::keys::k_down:
        return "k_down";
    case tavros::system::keys::k_print:
        return "k_print";
    case tavros::system::keys::k_print_screen:
        return "k_print_screen";
    case tavros::system::keys::k_insert:
        return "k_insert";
    case tavros::system::keys::k_delete:
        return "k_delete";
    case tavros::system::keys::k_help:
        return "k_help";
    case tavros::system::keys::k_0:
        return "k_0";
    case tavros::system::keys::k_1:
        return "k_1";
    case tavros::system::keys::k_2:
        return "k_2";
    case tavros::system::keys::k_3:
        return "k_3";
    case tavros::system::keys::k_4:
        return "k_4";
    case tavros::system::keys::k_5:
        return "k_5";
    case tavros::system::keys::k_6:
        return "k_6";
    case tavros::system::keys::k_7:
        return "k_7";
    case tavros::system::keys::k_8:
        return "k_8";
    case tavros::system::keys::k_9:
        return "k_9";
    case tavros::system::keys::k_A:
        return "k_A";
    case tavros::system::keys::k_B:
        return "k_B";
    case tavros::system::keys::k_C:
        return "k_C";
    case tavros::system::keys::k_D:
        return "k_D";
    case tavros::system::keys::k_E:
        return "k_E";
    case tavros::system::keys::k_F:
        return "k_F";
    case tavros::system::keys::k_G:
        return "k_G";
    case tavros::system::keys::k_H:
        return "k_H";
    case tavros::system::keys::k_I:
        return "k_I";
    case tavros::system::keys::k_J:
        return "k_J";
    case tavros::system::keys::k_K:
        return "k_K";
    case tavros::system::keys::k_L:
        return "k_L";
    case tavros::system::keys::k_M:
        return "k_M";
    case tavros::system::keys::k_N:
        return "k_N";
    case tavros::system::keys::k_O:
        return "k_O";
    case tavros::system::keys::k_P:
        return "k_P";
    case tavros::system::keys::k_Q:
        return "k_Q";
    case tavros::system::keys::k_R:
        return "k_R";
    case tavros::system::keys::k_S:
        return "k_S";
    case tavros::system::keys::k_T:
        return "k_T";
    case tavros::system::keys::k_U:
        return "k_U";
    case tavros::system::keys::k_V:
        return "k_V";
    case tavros::system::keys::k_W:
        return "k_W";
    case tavros::system::keys::k_X:
        return "k_X";
    case tavros::system::keys::k_Y:
        return "k_Y";
    case tavros::system::keys::k_Z:
        return "k_Z";
    case tavros::system::keys::k_lsuper:
        return "k_lsuper";
    case tavros::system::keys::k_rsuper:
        return "k_rsuper";
    case tavros::system::keys::k_menu:
        return "k_menu";
    case tavros::system::keys::k_numpad0:
        return "k_numpad0";
    case tavros::system::keys::k_numpad1:
        return "k_numpad1";
    case tavros::system::keys::k_numpad2:
        return "k_numpad2";
    case tavros::system::keys::k_numpad3:
        return "k_numpad3";
    case tavros::system::keys::k_numpad4:
        return "k_numpad4";
    case tavros::system::keys::k_numpad5:
        return "k_numpad5";
    case tavros::system::keys::k_numpad6:
        return "k_numpad6";
    case tavros::system::keys::k_numpad7:
        return "k_numpad7";
    case tavros::system::keys::k_numpad8:
        return "k_numpad8";
    case tavros::system::keys::k_numpad9:
        return "k_numpad9";
    case tavros::system::keys::k_multiply:
        return "k_multiply";
    case tavros::system::keys::k_add:
        return "k_add";
    case tavros::system::keys::k_subtract:
        return "k_subtract";
    case tavros::system::keys::k_decimal:
        return "k_decimal";
    case tavros::system::keys::k_divide:
        return "k_divide";
    case tavros::system::keys::k_F1:
        return "k_F1";
    case tavros::system::keys::k_F2:
        return "k_F2";
    case tavros::system::keys::k_F3:
        return "k_F3";
    case tavros::system::keys::k_F4:
        return "k_F4";
    case tavros::system::keys::k_F5:
        return "k_F5";
    case tavros::system::keys::k_F6:
        return "k_F6";
    case tavros::system::keys::k_F7:
        return "k_F7";
    case tavros::system::keys::k_F8:
        return "k_F8";
    case tavros::system::keys::k_F9:
        return "k_F9";
    case tavros::system::keys::k_F10:
        return "k_F10";
    case tavros::system::keys::k_F11:
        return "k_F11";
    case tavros::system::keys::k_F12:
        return "k_F12";
    case tavros::system::keys::k_F13:
        return "k_F13";
    case tavros::system::keys::k_F14:
        return "k_F14";
    case tavros::system::keys::k_F15:
        return "k_F15";
    case tavros::system::keys::k_F16:
        return "k_F16";
    case tavros::system::keys::k_F17:
        return "k_F17";
    case tavros::system::keys::k_F18:
        return "k_F18";
    case tavros::system::keys::k_F19:
        return "k_F19";
    case tavros::system::keys::k_F20:
        return "k_F20";
    case tavros::system::keys::k_semicolon:
        return "k_semicolon";
    case tavros::system::keys::k_equal:
        return "k_equal";
    case tavros::system::keys::k_comma:
        return "k_comma";
    case tavros::system::keys::k_minus:
        return "k_minus";
    case tavros::system::keys::k_period:
        return "k_period";
    case tavros::system::keys::k_slash:
        return "k_slash";
    case tavros::system::keys::k_grave_accent:
        return "k_grave_accent";
    case tavros::system::keys::k_lbracket:
        return "k_lbracket";
    case tavros::system::keys::k_backslash:
        return "k_backslash";
    case tavros::system::keys::k_rbracket:
        return "k_rbracket";
    case tavros::system::keys::k_apostrophe:
        return "k_apostrophe";
    case tavros::system::keys::k_numlock:
        return "k_numlock";
    case tavros::system::keys::k_scroll:
        return "k_scroll";
    case tavros::system::keys::k_lshift:
        return "k_lshift";
    case tavros::system::keys::k_rshift:
        return "k_rshift";
    case tavros::system::keys::k_lcontrol:
        return "k_lcontrol";
    case tavros::system::keys::k_rcontrol:
        return "k_rcontrol";
    case tavros::system::keys::k_lalt:
        return "k_lalt";
    case tavros::system::keys::k_ralt:
        return "k_ralt";
    default:
        return "<unknown>";
    }
}

tavros::core::string_view tavros::system::to_string(mouse_button bm) noexcept
{
    switch (bm) {
    case tavros::system::mouse_button::none:
        return "none";
    case tavros::system::mouse_button::left:
        return "left";
    case tavros::system::mouse_button::right:
        return "right";
    case tavros::system::mouse_button::middle:
        return "middle";
    case tavros::system::mouse_button::x_button1:
        return "x_button1";
    case tavros::system::mouse_button::x_button2:
        return "x_button2";
    default:
        return "<unknown>";
    }
}
